### ISSUE TITLE
ReferenceError: array is not defined when importing the fadeIn animation

### ISSUE THREAD

**Issue by csprocket777** [lifegadget/ui-icon#1]
I'm trying to import the 'fadeIn' animation per the instructions and am getting an error.

Here's the import code:

```
var app = new EmberApp({
    'ui-icon':{
        'animateOperation': 'append',
        'animate': ['fading_entrances/fadeIn.css']
    }
});
```

Here is the error:

```
 ember serve
version: 0.2.3
array is not defined
ReferenceError: array is not defined
    at Class.module.exports.included (/Users/chuckshipman/Documents/TM_git_repos/HR_TM_Dashboard/Development/hr-tm-dashboard/node_modules/ui-icon/index.js:56:36)
    at EmberApp.<anonymous> (/Users/chuckshipman/Documents/TM_git_repos/HR_TM_Dashboard/Development/hr-tm-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:312:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/Users/chuckshipman/Documents/TM_git_repos/HR_TM_Dashboard/Development/hr-tm-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:307:45)
    at new EmberApp (/Users/chuckshipman/Documents/TM_git_repos/HR_TM_Dashboard/Development/hr-tm-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:103:8)
    at Object.<anonymous> (/Users/chuckshipman/Documents/TM_git_repos/HR_TM_Dashboard/Development/hr-tm-dashboard/Brocfile.js:6:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

What am I doing wrong?

**Comment by yankeeinlondon** [comment]
Ahhh. You're out in front of me a little. I haven't yet incorporated the animations in a meaningful way. I have gotten much further with the [ui-input](https://github.com/lifegadget/ui-input) addon and since the animation functionality is all a mixin there I was planning on moving that over once I had stamped that as done. 

Sorry I can't give this immediate attention right now as I'm getting pulled in several directions at once. If you have the time to send me a PR that passes CI tests then I'm happy to accept that in otherwise I would just ask for your patience. I'll probably get to this in a few weeks time.
